FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir streamlit requests

COPY ui/ui.py ./ui.py
EXPOSE 8501
ENV BACKEND_URL="http://localhost:8000"
CMD ["streamlit", "run", "ui.py", "--server.port=8501", "--server.address=0.0.0.0"]